---
display-name: 'Gentle Glow'
package-name: GentleGlow
package-version: '1.5.0'

api-keys:
  # If you fork, please use your own API keys.
  tumblr: ku7A9H005pUoOwvgDNuAx1qNQoy7ukL5d3BKFt8flNC4bVB2me

include-files:
  - README.mdown
  - CHANGELOG.mdown

variants:
  RegularKind: null
  WhiteWashed: null
