---
display-name: 'Gentle Glow'
package-name: GentleGlow
package-version: '1.2.3'

include-files:
  - README.mdown
  - CHANGELOG.mdown

default-stylesheets: 

variants:
  RegularKind:
    - stylesheets/regular-kind.less
    - stylesheets/lib/*.less
  WhiteWashed:
    - stylesheets/white-washed.less
    - stylesheets/lib/*.less